<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Errors\Outcome\**" />
    <Compile Remove="Errors\Recoverable - Error Sequence\**" />
    <EmbeddedResource Remove="Errors\Outcome\**" />
    <EmbeddedResource Remove="Errors\Recoverable - Error Sequence\**" />
    <None Remove="Errors\Outcome\**" />
    <None Remove="Errors\Recoverable - Error Sequence\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Glitch\Glitch.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Glitch.Functional.FN">
      <Static>True</Static>
    </Using>
  </ItemGroup>

</Project>
