<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ParseResult.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Glitch.Functional\Glitch.Functional.csproj" />
  </ItemGroup>

</Project>
